### ISSUE TITLE
Photos are added twice to the collection

### ISSUE THREAD

**Issue by bumi** [bumi/tasveer#15]
After editing the collection already existing photos are added again to the collection. 
Thus we have duplicates.
Every photo should only be once in a collection but can be in multiple collections.

**Comment by ludoded** [comment]
Implemented @ commit c4ffb7252ffcf1ef3c252dd80ed4c220b656dbce

**Comment by bumi** [comment]
question: https://github.com/bumi/tasveer/commit/c4ffb7252ffcf1ef3c252dd80ed4c220b656dbce#commitcomment-33711651
